#!/usr/bin/env bash
#Script creating the a files PID

PID_FILE="/var/run/myscript.pid"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"; rm -f "$PID_FILE"; exit 0' SIGINT
trap 'rm -f "$PID_FILE"; exit 0' SIGQUIT

echo $$ > "$PID_FILE"

while true
do
    echo "To infinity and beyond"
    sleep 2
done
